name: CI
on: [push]

jobs:
  build-mod:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        java-version: ['8', '11', '16', '17']
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Print information about the run
        run: echo Java version is ${{ matrix.java-version }} and OS is ${{ matrix.os }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt-hotspot'
      - name: Set gradlew to executable
        run: chmod +x gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: extradebugging-dev-built-on-${{ matrix.os }}-using-java-${{matrix.java-version }}
          path: build/libs/*.jar