name: GitHub Actions Demo
on: [push]

jobs:
  build-mod:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04, windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt-hotspot'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ join(['extradebugging-built-on-', matrix.os, '.jar']) }}
          path: build/libs/*.jar